In [3]:
import numpy as np
import rasterio as rio
import matplotlib.pyplot as plt
import csv
from pathlib import Path

In [4]:
ndviFpath = r"d:\Images\ndvi_corrected\ndvi_corrected_stack30D.tif"

In [18]:
clusterFpath = r"d:\Images\ndvi_corrected\cluster_50_Output2.tif"

In [5]:
with rio.open(ndviFpath) as dst:
    ndviImg = dst.read()
    meta = dst.meta

In [19]:
with rio.open(clusterFpath) as dst:
    clusterImg = dst.read(1)
    clusterMeta = dst.meta

In [20]:
ndviImg.shape

(30, 1073, 1080)

In [ ]:
idx1 = np.where(clusterImg==1)

In [ ]:
idx1

(array([   0,    0,    0, ..., 1072, 1072, 1072], dtype=int64),
 array([104, 450, 487, ..., 594, 660, 795], dtype=int64))

In [ ]:
check = ndviImg[:,idx1[0],idx1[1]]

In [ ]:
check.shape

(30, 14824)

In [ ]:
check

array([[0.27769986, 0.25529075, 0.3394086 , ..., 0.20249678, 0.24211712,
        0.33009183],
       [0.22564185, 0.23208317, 0.33913043, ..., 0.16249014, 0.23776683,
        0.3199642 ],
       [0.17371601, 0.18650422, 0.3101367 , ..., 0.15852131, 0.17234726,
        0.2514916 ],
       ...,
       [0.21611072, 0.24125625, 0.22658502, ..., 0.267752  , 0.2514456 ,
        0.22292545],
       [0.16451275, 0.18502674, 0.17374241, ..., 0.23092471, 0.21959575,
        0.19368674],
       [0.22117269, 0.21898712, 0.22399151, ..., 0.28569016, 0.27734306,
        0.23897605]], dtype=float32)

In [ ]:
check2 = np.median(check, axis=1, keepdims=True)

In [ ]:
check2.shape

(31, 1)

In [ ]:
plt.plot(check2)

In [ ]:
plt.show()

In [21]:
meds = []
i = 1
while i<=50:
    idx = np.where(clusterImg==i)
    check = ndviImg[:,idx[0], idx[1]]
    checkMed = np.median(check, axis=1)
    meds.append(checkMed)
    i+=1
    del idx, check, checkMed

In [ ]:
meds

[array([0.27072424, 0.24576652, 0.20139873, 0.13670388, 0.10166366,
        0.08433986, 0.08316347, 0.07158837, 0.05918404, 0.05765243,
        0.08868913, 0.07870849, 0.09418837, 0.09832436, 0.12340037,
        0.16526678, 0.18910933, 0.2852773 , 0.32801637, 0.34702295,
        0.35164136, 0.3276189 , 0.3452899 , 0.4276793 , 0.39382723,
        0.36065432, 0.34240055, 0.2359353 , 0.1842895 , 0.23018864],
       dtype=float32),
 array([0.3130865 , 0.30564156, 0.2748429 , 0.21412498, 0.17469344,
        0.19522241, 0.2059861 , 0.18968794, 0.15333149, 0.13639024,
        0.19607088, 0.14938208, 0.16562939, 0.1408167 , 0.15612304,
        0.16094987, 0.14307663, 0.15380344, 0.15052342, 0.14793694,
        0.14276364, 0.14382926, 0.1432886 , 0.13380551, 0.12628981,
        0.1359106 , 0.12472761, 0.1163403 , 0.1076002 , 0.11386348],
       dtype=float32),
 array([0.23317307, 0.21991377, 0.1953295 , 0.15171227, 0.13129319,
        0.13285764, 0.14109926, 0.13497652, 0.116763  , 0.10822676,


In [ ]:
plt.ion()

In [ ]:
plt.plot(meds[3])

In [22]:
len(meds)

50

In [ ]:
np.sum((meds[1]-meds[2])**2, axis=0)

0.04809334

In [ ]:
mat = np.zeros((50,50))

In [ ]:
del i
i = 0
while i <50:
    j=0
    while j<=i:
        mat[i,j] = np.sum((meds[i]-meds[j])**2, axis=0)
        j+=1
    i+=1

In [76]:
plt.imshow(mat)
plt.colorbar()
plt.clim(0,1)

In [77]:
plt.show()

In [ ]:
del i
dmat = []
i = 0
while i <50:
    j=0
    while j<=i:
        dist = np.sum((meds[i]-meds[j])**2, axis=0)
        dmat.append([i,j,dist])
        j+=1
    i+=1


In [ ]:
dmat

[[0, 0, 0.0],
 [1, 0, 0.6013182],
 [1, 1, 0.0],
 [2, 0, 0.54502547],
 [2, 1, 0.04809334],
 [2, 2, 0.0],
 [3, 0, 0.11430532],
 [3, 1, 0.7250603],
 [3, 2, 0.67080367],
 [3, 3, 0.0],
 [4, 0, 0.14751832],
 [4, 1, 0.36066556],
 [4, 2, 0.41427764],
 [4, 3, 0.15814134],
 [4, 4, 0.0],
 [5, 0, 0.984181],
 [5, 1, 0.90706587],
 [5, 2, 1.0651449],
 [5, 3, 0.64045465],
 [5, 4, 0.45022392],
 [5, 5, 0.0],
 [6, 0, 0.0623674],
 [6, 1, 0.3324134],
 [6, 2, 0.32892728],
 [6, 3, 0.20907548],
 [6, 4, 0.06243241],
 [6, 5, 0.8189173],
 [6, 6, 0.0],
 [7, 0, 0.031215308],
 [7, 1, 0.4388882],
 [7, 2, 0.39861622],
 [7, 3, 0.07015881],
 [7, 4, 0.066951446],
 [7, 5, 0.72908497],
 [7, 6, 0.040969823],
 [7, 7, 0.0],
 [8, 0, 0.3521674],
 [8, 1, 0.27067965],
 [8, 2, 0.36201334],
 [8, 3, 0.59697556],
 [8, 4, 0.17518742],
 [8, 5, 0.87137014],
 [8, 6, 0.12825663],
 [8, 7, 0.29378685],
 [8, 8, 0.0],
 [9, 0, 0.57909805],
 [9, 1, 0.040838555],
 [9, 2, 0.08234538],
 [9, 3, 0.7843032],
 [9, 4, 0.35967478],
 [9, 5, 1.054069],
 

In [ ]:
distanceFile = r"D:\Images\ndvi_corrected\distanceFile.csv"

In [ ]:
with open(distanceFile, "w") as f:
    write = csv.writer(f)
    write.writerows(dmat)

In [ ]:
plt.plot(meds[6])

In [ ]:
plt.plot(meds[44])

In [ ]:
plt.show()

In [73]:
plt.clf()

In [75]:
outFolder = r"D:\Images\ClusterProducts\Median Cluster Graphs"
plt.ioff()
i = 0
while i < len(meds):
    plt.plot(meds[i])
    plt.title(f"{i}th Cluster")
    plotFpath = Path(outFolder, f"cluster_{i}.jpg")
    plt.ylim(0,0.7)
    plt.savefig(plotFpath)
    plt.clf()
    i += 1 

In [79]:
outMatFpath = r"D:\Images\ClusterProducts\Dmatrix.csv"
np.savetxt(outMatFpath, mat, delimiter=',', fmt="%2.3f")

In [1]:
from minisom import MiniSom

In [6]:
flatImg = ndviImg.reshape(ndviImg.shape[0],-1).T


In [8]:
flatImg

array([[0.32718894, 0.30013785, 0.27511537, ..., 0.20550671, 0.16878402,
        0.22414072],
       [0.28483275, 0.28679428, 0.25282016, ..., 0.1610573 , 0.14806303,
        0.17693152],
       [0.26506433, 0.2645813 , 0.24158715, ..., 0.16512243, 0.1461969 ,
        0.17915413],
       ...,
       [0.35468236, 0.38178724, 0.3534932 , ..., 0.0911792 , 0.09131075,
        0.08998989],
       [0.32722467, 0.34713763, 0.32903227, ..., 0.09138284, 0.08359592,
        0.08449848],
       [0.31974477, 0.3400732 , 0.3197183 , ..., 0.08663785, 0.08204651,
        0.0785554 ]], dtype=float32)

In [10]:
5*np.sqrt(flatImg.shape[0])

5382.471551248553

In [11]:
np.sqrt(5382)

73.3621155638249

In [12]:
som = MiniSom(74,74,flatImg.shape[1], sigma=0.3, learning_rate=0.1)

In [13]:
som.random_weights_init(flatImg)

In [14]:
som.train?

Signature:
som.train(
    data,
    num_iteration,
    random_order=False,
    verbose=False,
    use_epochs=False,
)
Docstring:
Trains the SOM.

Parameters
----------
data : np.array or list
    Data matrix.

num_iteration : int
    If use_epochs is False, the weights will be
    updated num_iteration times. Otherwise they will be updated
    len(data)*num_iteration times.

random_order : bool (default=False)
    If True, samples are picked in random order.
    Otherwise the samples are picked sequentially.

verbose : bool (default=False)
    If True the status of the training will be
    printed each time the weights are updated.

use_epochs : bool (default=False)
    If True the SOM will be trained for num_iteration epochs.
    In one epoch the weights are updated len(data) times and
    the learning rate is constat throughout a single epoch.
File:      c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-pack

In [16]:
meds.shape

NameError: name 'meds' is not defined

In [36]:
som = MiniSom(5,5,len(meds[1]), sigma=0.3, learning_rate=0.1)

In [37]:
som.random_weights_init(meds)

In [28]:
import copy

In [32]:
mySeries = copy.deepcopy(meds)

In [30]:
from sklearn.preprocessing import MinMaxScaler

In [33]:
for i in range(len(mySeries)):
    scaler = MinMaxScaler()
    mySeries[i] = MinMaxScaler().fit_transform(mySeries[i])
    mySeries[i]= mySeries[i].reshape(len(mySeries[i]))

ValueError: Expected 2D array, got 1D array instead:
array=[0.27072424 0.24576652 0.20139873 0.13670388 0.10166366 0.08433986
 0.08316347 0.07158837 0.05918404 0.05765243 0.08868913 0.07870849
 0.09418837 0.09832436 0.12340037 0.16526678 0.18910933 0.2852773
 0.32801637 0.34702295 0.35164136 0.3276189  0.3452899  0.4276793
 0.39382723 0.36065432 0.34240055 0.2359353  0.1842895  0.23018864].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [35]:
MinMaxScaler().fit_transform(meds[3])

ValueError: Expected 2D array, got 1D array instead:
array=[0.18117201 0.16542156 0.1494509  0.08466483 0.06877848 0.06301107
 0.07529055 0.08043478 0.08051293 0.08060162 0.12492826 0.10425983
 0.1729005  0.17868209 0.255794   0.30109453 0.28882885 0.38708445
 0.40755388 0.39434776 0.38097855 0.34047034 0.3497766  0.4045463
 0.36511377 0.32868633 0.30481654 0.19608517 0.15687963 0.15866742].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [38]:
som.train(mySeries, 10000)

In [39]:
win_map = som.win_map(meds)

In [40]:
win_map

defaultdict(list,
            {(0,
              2): [array([0.27072424, 0.24576652, 0.20139873, 0.13670388, 0.10166366,
                     0.08433986, 0.08316347, 0.07158837, 0.05918404, 0.05765243,
                     0.08868913, 0.07870849, 0.09418837, 0.09832436, 0.12340037,
                     0.16526678, 0.18910933, 0.2852773 , 0.32801637, 0.34702295,
                     0.35164136, 0.3276189 , 0.3452899 , 0.4276793 , 0.39382723,
                     0.36065432, 0.34240055, 0.2359353 , 0.1842895 , 0.23018864],
                    dtype=float32)],
             (0,
              0): [array([0.3130865 , 0.30564156, 0.2748429 , 0.21412498, 0.17469344,
                     0.19522241, 0.2059861 , 0.18968794, 0.15333149, 0.13639024,
                     0.19607088, 0.14938208, 0.16562939, 0.1408167 , 0.15612304,
                     0.16094987, 0.14307663, 0.15380344, 0.15052342, 0.14793694,
                     0.14276364, 0.14382926, 0.1432886 , 0.13380551, 0.12628981,
         

In [41]:
win_map.keys()

dict_keys([(0, 2), (0, 0), (1, 0), (3, 0), (2, 1), (0, 3), (1, 2), (4, 3), (2, 0), (3, 2), (3, 4), (4, 1), (4, 0), (2, 3), (4, 2), (1, 1), (3, 1), (2, 4), (4, 4), (2, 2), (1, 3), (0, 1), (1, 4), (0, 4)])

In [43]:
som_x = 5
som_y = 5
fig, axs = plt.subplots(som_x,som_y,figsize=(25,25))
fig.suptitle('Clusters')
for x in range(5):
    for y in range(som_y):
        cluster = (x,y)
        if cluster in win_map.keys():
            for series in win_map[cluster]:
                axs[cluster].plot(series,c="gray",alpha=0.5) 
            axs[cluster].plot(np.average(np.vstack(win_map[cluster]),axis=0),c="red")
            cluster_number = x*som_y+y+1
            axs[cluster].set_title(f"Cluster {cluster_number}")

In [44]:
plt.show()

In [45]:
win_map?

Type:        defaultdict
String form:
defaultdict(<class 'list'>, {(0, 2): [array([0.27072424, 0.24576652, 0.20139873, 0.13670388, 0.10 <...> 8378,
           0.32529724, 0.31270993, 0.21994536, 0.17634673, 0.21814106],
           dtype=float32)]})
Length:      24
File:        c:\program files\windowsapps\pythonsoftwarefoundation.python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\lib\collections\__init__.py
Docstring:  
defaultdict(default_factory=None, /, [...]) --> dict with default factory

The default factory is called without arguments to produce
a new value when a key is not present, in __getitem__ only.
A defaultdict compares equal to a dict with the same items.
All remaining arguments are treated the same as if they were
passed to the dict constructor, including keyword arguments.

In [46]:
som.win_map?

Signature: som.win_map(data, return_indices=False)
Docstring:
Returns a dictionary wm where wm[(i,j)] is a list with:
- all the patterns that have been mapped to the position (i,j),
  if return_indices=False (default)
- all indices of the elements that have been mapped to the
  position (i,j) if return_indices=True
File:      c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages\minisom.py
Type:      method